export const BODY_FAT_GAUGE_PERCENT_MIN = 3;
export const BODY_FAT_GAUGE_PERCENT_MAX_MALE = 45;
export const BODY_FAT_GAUGE_PERCENT_MAX_FEMALE = 50;
export const BODY_FAT_GAUGE_CATEGORY_COUNT = 7;
export const BODY_FAT_GAUGE_SEGMENT_DEGREES = 180 / BODY_FAT_GAUGE_CATEGORY_COUNT;
